Repository glmn/wb-private-api, pull requests merged in 2023-01, with the labels that each got.

#24 fix infinite recursion
  src/WBProduct.js
Labels: bug

#25 fix missing id field
  src/WBProduct.js
Labels: bug

#22 remove default UFO stores from query params
  src/WBPrivateAPI.js
  tests/WBPrivateAPI.test.js
Labels: hard-coded

#30 WB Изменил путь до картинок карточки товара
  index.js
  src/Constants.js
  src/Utils.js
  tests/Utils.test.js
Labels: bug, wb-changes

#31 fix feedbacks NPE
  src/WBProduct.js
Labels: bug
